PREFIX coursesonto: <https://w3id.org/coursesonto#>
PREFIX schema: <http://schema.org/>
PREFIX edutype: <https://w3id.org/coursesonto/kos/educational-type/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?course ?material ?theory WHERE {
	?course schema:hasCourseInstance ?courseSession .
	?coursesSession coursesonto:containsResource ?material .
	?material coursesonto:hasType ?theory .
	?theory skos:hasTopConcept edutype:theory .
	FILTER(?course = <Y>) # replace Y with URI of the given Course
}